ARENA_ENV_PREFIX = 'Arena-'
AGENT_ID_PREFIX = "agent"
POLICY_ID_PREFIX = "policy"
CHECKPOINT_PATH_PREFIX = "learning_agent/"
CHECKPOINT_PATH_POPULATION_PREFIX = "p_"
CHECKPOINT_PATH_ITERATION_PREFIX = "i_"
